# Configuração de patrocínio para TSiJUKEBOX
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors username
github: [B0yZ4kr14]

# Patreon username
# patreon: 

# Open Collective username
# open_collective: 

# Ko-fi username
# ko_fi: 

# Buy Me a Coffee username
# buy_me_a_coffee: 

# Custom funding URLs (max 4)
custom: 
  - https://github.com/sponsors/B0yZ4kr14
